[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "rd_ctt"
version = "0.1.4"
description = "Redis constants for Lowell Instruments"
dependencies = [
]